//TobExEE
#ifndef P_ANIMCORE_H
#define P_ANIMCORE_H

#ifdef __2014

  #define CANIMATIONSOUNDLIST_PLAYPRIMEDSOUND	0X5770E0

  #define CANIMATION_PLAYCURRENTSEQUENCESOUND	0X67BAF0

#elif
#endif

#endif //P_ANIMCORE_H