//TobExEE
#ifndef P_CMAPSS_H
#define P_CMAPSS_H

#ifdef __2014

  #define	IECMAPSTRINGTOSTRING_CONSTRUCT	0X7D02D0
  #define	IECMAPSTRINGTOSTRING_INITHASHTABLE	0X7D3590
  #define	IECMAPSTRINGTOSTRING_REMOVEALL	0X7D0360
  #define	IECMAPSTRINGTOSTRING_DECONSTRUCT	0X7D0420
  #define	IECMAPSTRINGTOSTRING_LOOKUP	0X7D0660
  #define	IECMAPSTRINGTOSTRING_OPARRAY	0X7D06A0
  #define	IECMAPSTRINGTOSTRING_REMOVEKEY	0X7D0730
  #define	IECMAPSTRINGTOSTRING_GETNEXTASSOC	0X7D07D0

  #define	IECMAPSTRINGTOSTRING_GETASSOCAT	0X7D0590

#elif
#endif

#endif //P_CMAPSS_H