//TobExEE
#ifndef P_ENGWORLD_H
#define P_ENGWORLD_H

#ifdef __2014

  #define CSCREENWORLD_PRINTTOCONSOLE6	0X66BCA0
  #define CSCREENWORLD_PRINTTOCONSOLE4	0X66BE70

#elif
#endif

#endif //P_ENGWORLD_H