//TobExEE
#ifndef P_INFGAME_H
#define P_INFGAME_H

#ifdef __2014

  #define CWORLDTIMER_UNPAUSEGAME	0X57A870

  #define CINFGAME_GETWORLDTIMER	0X408CD0
  #define CINFGAME_GETSCRIPTPARSER	0X497AE0

#elif
#endif

#endif //P_INFGAME_H