//TobExEE
#ifndef P_INFGAME_H
#define P_INFGAME_H

#ifdef __2014

  #define CWORLDTIMER_UNPAUSEGAME	0X57A870

  #define CINFGAME_GETWORLDTIMER	0X408CD0
  #define CINFGAME_GETSCRIPTPARSER	0X497AE0
  #define CINFGAME_SETLOSECUTSCENE	0X5B5040

  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP1	0x4ACD75
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP2	0x4ACDAB
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP3	0x4C5106
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP4	0x4C5CE3
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP5	0x4C5D19
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP6	0x4D1B79
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP7	0x65C22B
  #define DETOUR_CINFGAME_SETLOSECUTSCENE_EIP8	0x6653EC

#elif
#endif

#endif //P_INFGAME_H