//TobExEE
#ifndef P_MSGCORE_H
#define P_MSGCORE_H

#ifdef __2014

  #define CMESSAGEMODIFYVARIABLE_CONSTRUCT	0X4741E0
  #define CMESSAGEMODIFYVARIABLE_DECONSTRUCT	0X4EFBE0

  #define CMESSAGEHANDLER_ADDMESSAGE	0X5265E0


#elif
#endif

#endif //P_MSGCORE_H