//TobExEE
#ifndef P_OBJCORE_H
#define P_OBJCORE_H

#ifdef __2014

  #define CGAMESPRITE_EVALUATETRIGGER	0X4508F0
  #define CGAMESPRITE_CLEARALLACTIONS	0X44BC63
  #define CGAMESPRITE_EXECUTEACTION	0X44BF50
  #define CGAMESPRITE_GETTOPACTION	0X45AE50
  #define CGAMESPRITE_QUEUEACTIONS	0X45B590

  #define CGAMEOBJECTARRAY_GETOBJECT	0X5949E0

#elif
#endif

#endif //P_OBJCORE_H