//TobExEE
#ifndef P_OBJCRE_H
#define P_OBJCRE_H

#ifdef __2014

  #define CCREATUREOBJECT_EVALUATETRIGGER	0x70ECF0
  #define CCREATUREOBJECT_EXECUTEACTION	0X702860

  #define CCREATUREOBJECT_GETDERIVEDSTATS	0x408ED0
#elif
#endif

#endif //P_OBJCRE_H