//TobExEE
#ifndef P_PATCH_H
#define P_PATCH_H

#ifdef __2014

  #define PATCH_DEBUG_LOGMISSINGRES_CKEYTABLE_FINDKEY1 0X7B0BA7
  #define PATCH_DEBUG_LOGMISSINGRES_CKEYTABLE_FINDKEY2 0X7B0C9D

  #define PATCH_FX_STONESKINDISABLECOLOUR_CEFFECTSTONESKIN_APPLYEFFECT 0X4D77B1

  #define PATCH_FX_DROPINVDISINTEGRATE_CEFFECTINSTANTDEATH_APPLYEFFECT 0x4AE3F9
  #define PATCH_FX_DROPINVFROZENDEATH_CEFFECTINSTANTDEATH_APPLYEFFECT 0x4AE148
  #define PATCH_FX_DROPINVSTONEDEATH_CEFFECTINSTANTDEATH_APPLYEFFECT 0x4ADF25

  #define PATCH_ENGINE_ALLOWEQUIPARMORCOMBAT_CRULETABLES_TRYMODIFYEQUIPSLOT 0X5A9C3C

  #define PATCH_ENGINE_DISABLEINVPAUSESP_CSCREENINVENTORY_INIT 0X614446
  #define PATCH_ENGINE_DISABLEINVPAUSESP_CSCREENINVENTORY_DEINIT 0X614567
  #define PATCH_ENGINE_DISABLEINVPAUSESP_CSCREENINVENTORY_UPDATEPAUSESTATUS 0X61A1AE

  #define PATCH_ENGINE_AUTOPAUSEALLSP_CCREATUREOBJECT_SETAUTOPAUSEINFO 0X6F4EC6

#elif
#endif

#endif //P_PATCH_H