//TobExEE
#ifndef P_PATCH_H
#define P_PATCH_H

#ifdef __2014

  #define PATCH_DEBUG_LOGMISSINGRES_CKEYTABLE_FINDKEY1 0X7B0BA7
  #define PATCH_DEBUG_LOGMISSINGRES_CKEYTABLE_FINDKEY2 0X7B0C9D

#elif
#endif

#endif //P_PATCH_H